/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.front.swing.carregamento;

import app.front.swing.login.Main;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author gustavo.felix
 */
public class CarregamentoInicial extends javax.swing.JFrame {

    /**
     * Creates new form Carregamento
     */
    public CarregamentoInicial() {
        
        UIManager.put("nimbusOrange", new Color(50,151,248));
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {

                for (int i = 0; i < 100; i++) {
                    jProgressBar1.setValue(i);
                    textoCarregamento(i);
                }

                dispose();
                try {
                    new Main().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(CarregamentoInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        t.start();

    }
        public void textoCarregamento(int contagem){
        if (contagem < 60) {
            textoEspera.setAlignmentX(CENTER_ALIGNMENT);
            textoEspera.setText("Estamos preparando tudo.");
            sleepBarraDeProcesso(50);
            textoEspera.setText("Estamos preparando tudo..");
            sleepBarraDeProcesso(50);
            textoEspera.setText("Estamos preparando tudo...");
          
            
        } else if (contagem > 70) {
            textoEspera.setHorizontalAlignment(0);
            sleepBarraDeProcesso(10);
            textoEspera.setText("Prontinho!");
        }
    }
    
    
    public void sleepBarraDeProcesso() {
        try {
                        Thread.sleep(50);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(CarregamentoInicial.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }
    
        public void sleepBarraDeProcesso(Integer i) {
        try {
                        Thread.sleep(i);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(CarregamentoInicial.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new app.front.swing.utils.PanelGradiente();
        panelBorder1 = new app.front.swing.utils.PanelBorder();
        textoEspera = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelGradiente1.setColorPrimario(new java.awt.Color(153, 255, 255));
        panelGradiente1.setColorSecundario(new java.awt.Color(51, 102, 255));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        textoEspera.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        textoEspera.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoEspera.setText("Estamos preparando tudo..");
        panelBorder1.add(textoEspera);
        textoEspera.setBounds(100, 50, 450, 50);
        panelBorder1.add(jProgressBar1);
        jProgressBar1.setBounds(20, 354, 620, 10);

        panelGradiente1.setLayer(panelBorder1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelGradiente1Layout = new javax.swing.GroupLayout(panelGradiente1);
        panelGradiente1.setLayout(panelGradiente1Layout);
        panelGradiente1Layout.setHorizontalGroup(
            panelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradiente1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelGradiente1Layout.setVerticalGroup(
            panelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradiente1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarregamentoInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarregamentoInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarregamentoInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarregamentoInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarregamentoInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private app.front.swing.utils.PanelBorder panelBorder1;
    private app.front.swing.utils.PanelGradiente panelGradiente1;
    private javax.swing.JLabel textoEspera;
    // End of variables declaration//GEN-END:variables
}
