/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.front.swing.home;

import app.backend.app.utils.PrimeiraLetraMaiuscula;
import app.front.swing.login.Main;
import app.front.swing.planos.PlanoBasic;
import app.front.swing.planos.PlanoPro;
import app.front.swing.planos.PlanoStarter;
import app.front.swing.planos.PlanosAll;
import app.front.swing.welcome.BoasVindas;
import app.front.swing.welcome.BoasVindasFuncionario;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gustavo.felix
 */
public class Home extends javax.swing.JFrame {

    private static String usuario;

    private static BoasVindasFuncionario boasVindasUsuario;
    
    private static BoasVindas boasVindas;

    private static PlanoPro planoPro;

    private static PlanoStarter planoStarter;

    private static PlanoBasic planoBasic;
    
    private static PlanosAll planos;

    public Home(String usuario) {
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());

        this.usuario = usuario;

        PrimeiraLetraMaiuscula letraMaiuscula = new PrimeiraLetraMaiuscula();

        boasVindas = new BoasVindas(this.usuario);
        planoBasic = new PlanoBasic(usuario);
        planoStarter = new PlanoStarter(usuario);
        planoPro = new PlanoPro(usuario);
        planos = new PlanosAll(usuario);
        
        boasVindas.voltarParaLogin(irParaLogin());
        
        panelSlide1.setAnimate(100);
        panelSlide1.init(boasVindas,planoBasic,planoStarter,planoPro,planos);

        boasVindas.assinaturaActionListener(irParaPlano());
        
        planoPro.voltarParaHome(irParaHome());
        planoStarter.voltarParaHome(irParaHome());
        planoBasic.voltarParaHome(irParaHome());
        planos.voltarParaHome(irParaHome());
    
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente3 = new app.front.swing.utils.PanelGradiente();
        panelBorder1 = new app.front.swing.utils.PanelBorder();
        panelSlide1 = new app.front.swing.utils.PanelSlide();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelGradiente3.setColorPrimario(new java.awt.Color(153, 255, 255));
        panelGradiente3.setColorSecundario(new java.awt.Color(51, 51, 255));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        panelSlide1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelSlide1Layout = new javax.swing.GroupLayout(panelSlide1);
        panelSlide1.setLayout(panelSlide1Layout);
        panelSlide1Layout.setHorizontalGroup(
            panelSlide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        panelSlide1Layout.setVerticalGroup(
            panelSlide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        panelBorder1.setLayer(panelSlide1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelSlide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelSlide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelGradiente3.setLayer(panelBorder1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelGradiente3Layout = new javax.swing.GroupLayout(panelGradiente3);
        panelGradiente3.setLayout(panelGradiente3Layout);
        panelGradiente3Layout.setHorizontalGroup(
            panelGradiente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradiente3Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelGradiente3Layout.setVerticalGroup(
            panelGradiente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradiente3Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGradiente3, javax.swing.GroupLayout.DEFAULT_SIZE, 1233, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelGradiente3, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Home(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.front.swing.utils.PanelBorder panelBorder1;
    private app.front.swing.utils.PanelGradiente panelGradiente3;
    private app.front.swing.utils.PanelSlide panelSlide1;
    // End of variables declaration//GEN-END:variables

    private ActionListener irParaPlano() {
        return new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                switch (boasVindas.getPlano()) {
                    case ("Basic"):
                        panelSlide1.show(1);
                        System.out.println(boasVindas.getPlano());
                        break;
                    case "Starter":
                        panelSlide1.show(2);
                        System.out.println(boasVindas.getPlano());

                        break;
                    case "Pro":
                        panelSlide1.show(3);
                        System.out.println(boasVindas.getPlano());
                        break;
                    case "N":
                        panelSlide1.show(4);
                }
            }
        };
    }

    private ActionListener irParaHome() {
        return new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panelSlide1.show(0);
            }
        };
    }

    private ActionListener irParaLogin() {
        return new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    dispose();
                    new Main().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
    }
}
